# Generated by Django 2.2.24 on 2021-06-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseaffils', '0005_auto_20200318_1543'),
        ('main', '0002_auto_20210601_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseaffils.Course'),
            preserve_default=False,
        ),
    ]
