# Generated by Django 2.2.24 on 2021-07-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210614_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='multiple_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
