# Generated by Django 2.2.24 on 2021-07-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210708_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='scoring_scheme',
            field=models.IntegerField(default=1),
        ),
    ]
