# Generated by Django 2.2.24 on 2021-07-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_quiz_scoring_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='scoring_scheme',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Custom')], default=1),
        ),
    ]
