# Generated by Django 2.2.24 on 2021-07-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210709_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='randomize',
            field=models.BooleanField(default=False, verbose_name='Randomize the quiz questions'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='show_answers',
            field=models.BooleanField(default=False, verbose_name='Show the correct answers on submission'),
        ),
    ]
