# Generated by Django 2.2.24 on 2021-07-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210712_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresponse',
            name='marker',
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='selected_position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuestionResponseMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField()),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Marker')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.QuestionResponse')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
    ]
