# Generated by Django 2.2.24 on 2021-08-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210720_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='show_answers',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='scoring_scheme',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard'), (3, 'Custom')], default=1),
        ),
    ]
