# Generated by Django 2.2.24 on 2021-08-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210803_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_answers',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Never'), (1, 'Immediately after quiz submission'), (2, 'On given date')], default=1),
        ),
    ]
