# Generated by Django 2.2.24 on 2021-08-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_quiz_show_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_answers_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
