# Generated by Django 2.2.24 on 2021-08-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210824_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='scoring_scheme',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Consequence'), (1, 'Medium Consequence'), (2, 'Hard Consequence'), (3, 'Custom')], default=1),
        ),
    ]
