# Generated by Django 2.2.24 on 2021-08-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210827_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='scoring_scheme',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Consequences'), (1, 'Moderate Consequences'), (2, 'High Consequences'), (3, 'Custom')], default=1),
        ),
    ]
