# Generated by Django 2.2.24 on 2021-10-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_quiz_time'),
        ('main', '0015_auto_20210830_1353'),
    ]

    operations = [
    ]
