# Generated by Django 3.2.13 on 2022-06-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_merge_20211025_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
